package com.wanfadger.AdministrativeareaApi.shared.util;

import org.springframework.cache.interceptor.KeyGenerator;
import org.springframework.stereotype.Component;

import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Custom cache key generator for query parameter maps
 * 
 * This ensures deterministic cache keys regardless of Map iteration order.
 * Keys are generated by sorting map entries alphabetically and joining them.
 * 
 * Example:
 *   Input: {type="REGION", code="123", partOf="456"}
 *   Output: "code=123&partOf=456&type=REGION"
 * 
 * This prevents cache misses due to non-deterministic Map.toString() behavior.
 */
@Component("queryMapKeyGenerator")
public class QueryMapKeyGenerator implements KeyGenerator {

    @Override
    public Object generate(Object target, Method method, Object... params) {
        if (params.length == 0) {
            return method.getName();
        }

        // Handle Map<String, String> query parameters
        if (params[0] instanceof Map) {
            @SuppressWarnings("unchecked")
            Map<String, String> queryMap = (Map<String, String>) params[0];
            
            if (queryMap == null || queryMap.isEmpty()) {
                return method.getName() + ":default";
            }

            // Generate deterministic key by sorting entries
            String key = queryMap.entrySet().stream()
                    .sorted(Map.Entry.comparingByKey())
                    .map(entry -> {
                        String k = entry.getKey() != null ? entry.getKey() : "";
                        String v = entry.getValue() != null ? entry.getValue() : "";
                        return k + "=" + v;
                    })
                    .collect(Collectors.joining("&"));

            return method.getName() + ":" + key;
        }

        // Fallback for other parameter types
        return method.getName() + ":" + Arrays.toString(params);
    }
}
